site_name: Hagrid By Freshworks
site_dir: docs
docs_dir: wiki

theme:
  name: material
  font:
    text: Roboto
  custom_dir: wiki/custom_theme/
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress

extra_javascript:
  - assets/javascript/github-issue.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - include-markdown
  - glightbox
  
nav:
  - "Home": index.md
  # - Get Started:
  #     - Basic Concepts: get_start/concepts.md
  #     - Development: get_start/develop.md

  # Below section, we explain advance concepts from user perspective
  - Use cases:
      - Steps: usecases/steps.md
      - Beans: usecases/beans.md
      - Assets: usecases/assets.md
      - Consumer: usecases/consumer.md
      - Error Handling: usecases/error_handling.md
      - Analytics: usecases/analytics.md
      - Performance: usecases/performance.md


  - Versions:
      - 4.1.0: versions/4.1.0.md
      - 4.0.0: versions/4.0.0.md

  - DSR By Module:
    - Introduction: dsr/main.md
    - Traverser DSR: dsr/traverser.md
    - Processor DSR: dsr/processor.md
    - Infra DSR: dsr/infra.md
    - Across DSR: dsr/cut-across.md
    
  - Services:
    - Combined View: services/high_level.md
    - Traverser Services: services/traverser_services.md
    - Processor Services: services/processor_services.md
    - Shared Services: services/shared_services.md
    - Infra Services: services/infra_services.md

  # Below section, we explain advance concepts from core developer perspective
#  - Internals:
#      - High Level: internals/highlevel.md
#      - Design: internals/design.md
#      - Low Level: internals/lowlevel.md
#      - Concepts: internals/high_level.md
#      - Meetings: internals/meetings.md


#  - Glossary:
#    - glossary/glossary.md

