spring.application.name = hagrid
spring.threads.virtual.enabled=true
server.tomcat.threads.max=1000
server.port=8080


management.endpoints.web.path-mapping.prometheus=/metrics
management.tracing.sampling.probability=1.0
management.tracing.propagation.type=b3
management.endpoints.web.exposure.include=*
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.mongo.command.enabled=false
management.metrics.mongo.connectionpool.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
spring.connector.secret=asdfasdfasdgasdgasdfgasdgavasdfw
